export type ClaimType = {
  slug: string
  title: string
  icon: string
  tagline: string
  description: string
  commonScenarios: string[]
  whatYouNeed: string[]
  maxAmount: { CA: string; TX: string; FL: string }
  timeLimit: string
  tips: string[]
}

export const CLAIMS: ClaimType[] = [
  {
    slug: 'landlord-tenant',
    title: 'Landlord / Tenant Disputes',
    icon: '🏠',
    tagline: 'Get your security deposit back. Hold your landlord accountable.',
    description: 'Landlord-tenant disputes are the most common small claims cases in the US. Whether your landlord is wrongfully withholding your security deposit, failing to make repairs, or violating your lease, small claims court is your fastest and cheapest path to justice.',
    commonScenarios: [
      'Security deposit not returned after move-out',
      'Landlord refusing to make necessary repairs',
      'Illegal lockout or eviction',
      'Rent overcharge or unauthorized fees',
      'Property damage caused by landlord negligence',
      'Lease agreement violations',
    ],
    whatYouNeed: [
      'Your lease or rental agreement',
      'Move-in and move-out inspection reports',
      'Photos of the rental unit condition',
      'Written communication with your landlord',
      'Receipts for any repairs you paid for yourself',
      'Bank statements showing rent payments',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years depending on state and claim type',
    tips: [
      'Send a demand letter first — landlords often pay up to avoid court',
      'Document everything in writing, not phone calls',
      'Take photos the day you move out',
      'California law requires landlords to return deposits within 21 days',
    ],
  },
  {
    slug: 'breach-of-contract',
    title: 'Breach of Contract',
    icon: '📝',
    tagline: 'When someone breaks their promise, hold them to it.',
    description: 'A breach of contract occurs when one party fails to fulfill their obligations under a written or oral agreement. Small claims court is ideal for recovering damages when a contractor didn\'t finish a job, a seller didn\'t deliver goods, or a service provider failed to deliver.',
    commonScenarios: [
      'Contractor who took payment but didn\'t complete the work',
      'Seller who didn\'t deliver purchased goods',
      'Service provider who failed to perform as agreed',
      'Freelancer or vendor who didn\'t deliver',
      'Business that broke a written agreement',
      'Unpaid invoices for services rendered',
    ],
    whatYouNeed: [
      'The original written contract or agreement',
      'Proof of payment (receipts, bank statements)',
      'Written communications (emails, texts)',
      'Evidence of the breach (photos, documentation)',
      'Records of any attempts to resolve the issue',
      'Invoices or estimates for any remediation costs',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-6 years depending on written vs oral contract',
    tips: [
      'Written contracts are stronger than verbal agreements',
      'Document all your losses — include time, money, and consequential damages',
      'Send a certified demand letter before filing',
      'Keep all text messages and emails as evidence',
    ],
  },
  {
    slug: 'property-damage',
    title: 'Property Damage',
    icon: '🚗',
    tagline: 'Someone damaged your property. Make them pay for it.',
    description: 'If someone damaged your vehicle, home, or personal property through negligence or intentional acts, you can sue for repair costs, replacement value, and related expenses in small claims court.',
    commonScenarios: [
      'Car accident where the other driver was at fault',
      'Neighbor\'s tree fell on your property',
      'Contractor caused damage during a job',
      'Vehicle damaged in a parking lot hit-and-run',
      'Personal property damaged by a business',
      'Water damage caused by a neighbor',
    ],
    whatYouNeed: [
      'Photos of the damage',
      'Police or incident report if applicable',
      'Repair estimates from licensed contractors',
      'Receipts for any repairs already completed',
      'Insurance correspondence',
      'Witness contact information',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-3 years for property damage claims',
    tips: [
      'Get at least two independent repair estimates',
      'File a police report even for minor incidents',
      'Photograph the damage immediately',
      'Don\'t repair before documenting — courts need to see the original damage',
    ],
  },
  {
    slug: 'consumer-product',
    title: 'Defective Products',
    icon: '🛍️',
    tagline: 'Defective product? You deserve a refund or replacement.',
    description: 'If you purchased a product that was defective, dangerous, or not as described, you may be entitled to a full refund, replacement, or compensation for any harm caused. Small claims court lets you take on even large companies without a lawyer.',
    commonScenarios: [
      'Product stopped working shortly after purchase',
      'Item was not as described or advertised',
      'Defective product caused injury or property damage',
      'Company refused to honor warranty',
      'Counterfeit or fake product sold as genuine',
      'Online purchase that arrived damaged or never arrived',
    ],
    whatYouNeed: [
      'Original receipt or proof of purchase',
      'Photos of the defective product',
      'Written communications with the seller',
      'Warranty documentation',
      'Medical records if injury occurred',
      'Expert opinion for technical defects',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years depending on claim type',
    tips: [
      'Keep the defective product as evidence',
      'File a BBB complaint before going to court — some companies will settle',
      'You can sue both the manufacturer AND the retailer',
      'Document all attempts to get a refund or replacement',
    ],
  },
  {
    slug: 'unpaid-wages',
    title: 'Unpaid Wages',
    icon: '💰',
    tagline: 'Your employer owes you. Collect what you earned.',
    description: 'If your employer has withheld wages, failed to pay overtime, made unauthorized deductions, or misclassified you as a contractor to avoid paying benefits, small claims court is one of several options to recover what you\'re owed.',
    commonScenarios: [
      'Employer withheld final paycheck',
      'Overtime hours not paid at proper rate',
      'Unauthorized deductions from paycheck',
      'Employer didn\'t pay promised bonuses or commissions',
      'Misclassified as independent contractor',
      'Minimum wage violations',
    ],
    whatYouNeed: [
      'Pay stubs and payment records',
      'Employment contract or offer letter',
      'Time records or timesheets',
      'Written communications about pay',
      'Tax forms (W-2 or 1099)',
      'Bank statements showing deposits',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-3 years for wage claims',
    tips: [
      'California has some of the strongest worker protections — employers may owe waiting time penalties',
      'File with the Labor Commissioner as an alternative to small claims',
      'Keep personal copies of all pay records',
      'Document every hour worked with dates and times',
    ],
  },
  {
    slug: 'car-accident',
    title: 'Car Accidents',
    icon: '🚗',
    tagline: 'Get compensated for vehicle damage and expenses.',
    description: 'If you were in a car accident caused by another driver and your insurance doesn\'t fully cover your losses, small claims court lets you recover the difference — including vehicle damage, rental car costs, medical expenses, and lost wages.',
    commonScenarios: [
      'Other driver was at fault but won\'t pay',
      'Insurance settlement didn\'t cover full damages',
      'Hit and run damage to parked vehicle',
      'Uninsured driver caused the accident',
      'Dispute over fault or damage amount',
      'Rental car costs not covered by insurance',
    ],
    whatYouNeed: [
      'Police accident report',
      'Photos of vehicle damage and accident scene',
      'Insurance correspondence',
      'Repair estimates and receipts',
      'Medical bills if applicable',
      'Witness contact information',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-3 years for car accident claims',
    tips: [
      'Always file a police report at the scene',
      'Get the other driver\'s insurance and license information',
      'Take photos before moving any vehicles',
      'See a doctor even if you feel fine — injuries can appear days later',
    ],
  },
  {
    slug: 'personal-injury',
    title: 'Personal Injury',
    icon: '🩹',
    tagline: 'Injured due to someone else\'s negligence? Fight back.',
    description: 'Personal injury claims cover situations where someone else\'s negligence or intentional actions caused you physical harm. If your medical bills and losses are within the small claims limit, you can resolve your case faster and cheaper in small claims court.',
    commonScenarios: [
      'Slip and fall on someone else\'s property',
      'Dog bite or animal attack',
      'Injury at a business due to unsafe conditions',
      'Sports or recreational activity injury caused by negligence',
      'Assault causing physical injury',
      'Food poisoning at a restaurant',
    ],
    whatYouNeed: [
      'Medical records and bills',
      'Photos of the injury and accident scene',
      'Incident report from the property owner',
      'Witness statements',
      'Documentation of lost wages',
      'Expert medical opinion if needed',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2 years for personal injury in most states',
    tips: [
      'Seek medical attention immediately — it documents the injury',
      'Report the incident to the property owner in writing',
      'Note the names and contact info of all witnesses',
      'Keep a daily journal of pain and limitations',
    ],
  },
  {
    slug: 'debt-collection',
    title: 'Debt Collection',
    icon: '💳',
    tagline: 'Collect what you\'re owed. Or fight back against collectors.',
    description: 'Small claims court works both ways for debt disputes — you can use it to collect money you\'re owed, or to sue a debt collector for violating the Fair Debt Collection Practices Act (FDCPA), which prohibits harassment, false statements, and unfair practices.',
    commonScenarios: [
      'Someone borrowed money and won\'t repay',
      'Business owes you payment for services',
      'Debt collector used illegal tactics',
      'Collection agency pursuing invalid debt',
      'Credit card dispute resulting in wrongful charges',
      'Promissory note not honored',
    ],
    whatYouNeed: [
      'Loan agreement or promissory note',
      'Evidence of the money transferred',
      'Written communications about repayment',
      'Bank statements showing the transaction',
      'Records of debt collector communications',
      'Cease and desist letters sent',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '3-6 years depending on debt type',
    tips: [
      'A simple IOU signed by both parties is valid evidence',
      'FDCPA violations can net you up to $1,000 in statutory damages',
      'Record all collector calls where legally permitted',
      'Send all communications via certified mail',
    ],
  },
  {
    slug: 'dog-bite',
    title: 'Dog Bites',
    icon: '🐕',
    tagline: 'Dog bite victims deserve compensation. We can help you get it.',
    description: 'In most states, dog owners are strictly liable for bites — meaning you don\'t have to prove the owner knew the dog was dangerous. If a dog bit you or your pet, you can sue for medical expenses, pain and suffering, and lost wages.',
    commonScenarios: [
      'Dog bit you or a family member',
      'Dog attacked and injured your pet',
      'Dog knocked you down causing injury',
      'Stray or neighbor\'s dog caused damage',
      'Dog bite at a business or public place',
    ],
    whatYouNeed: [
      'Medical records and bills for treatment',
      'Photos of the bite wounds',
      'Veterinary records if your pet was attacked',
      'Dog owner\'s contact and insurance information',
      'Police or animal control report',
      'Witness statements',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2 years in most states',
    tips: [
      'Report the bite to animal control immediately',
      'Get the dog\'s vaccination records',
      'California has strict liability — owner pays even if dog never bit before',
      'Document all medical treatment and follow-up care',
    ],
  },
  {
    slug: 'auto-repair',
    title: 'Auto Repair Disputes',
    icon: '🔧',
    tagline: 'Mechanic overcharged you or didn\'t fix your car? Sue them.',
    description: 'Auto repair fraud and incompetence cost consumers billions each year. If a mechanic overcharged you, did unauthorized work, failed to fix your vehicle, or caused additional damage, small claims court is the right venue.',
    commonScenarios: [
      'Mechanic charged for work not performed',
      'Repair didn\'t fix the original problem',
      'Shop caused additional damage during repair',
      'Unauthorized work performed without approval',
      'Parts not replaced as billed',
      'Estimate was significantly exceeded without notice',
    ],
    whatYouNeed: [
      'Original repair estimate',
      'Final invoice and receipt',
      'Written authorization for work',
      'Second opinion from another mechanic',
      'Photos of before and after',
      'Written communications with the shop',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years',
    tips: [
      'Always get a written estimate before authorizing work',
      'California requires written authorization for work over $100',
      'Get a second opinion from another shop',
      'File a complaint with the Bureau of Automotive Repair (CA)',
    ],
  },
  {
    slug: 'slip-and-fall',
    title: 'Slip & Fall Accidents',
    icon: '⚠️',
    tagline: 'Injured on someone else\'s property? They may owe you.',
    description: 'Property owners have a legal duty to maintain safe conditions. If you slipped, tripped, or fell due to a hazardous condition that the property owner knew about or should have known about, you may be entitled to compensation for your injuries.',
    commonScenarios: [
      'Slipped on wet floor without warning sign',
      'Tripped on broken sidewalk or pavement',
      'Fell due to poor lighting in a parking lot',
      'Stairway defect caused a fall',
      'Unsecured carpet or flooring caused injury',
      'Fell in a grocery store or retail location',
    ],
    whatYouNeed: [
      'Incident report from the property owner',
      'Photos of the hazardous condition',
      'Medical records and bills',
      'Witness contact information',
      'Surveillance footage if available',
      'Documentation of lost wages',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2 years for premises liability claims',
    tips: [
      'Report the incident immediately and get a written incident report',
      'Don\'t let them clean up the hazard before photos are taken',
      'See a doctor the same day',
      'Preserve the shoes you were wearing as evidence',
    ],
  },
  {
    slug: 'lost-package',
    title: 'Lost or Damaged Packages',
    icon: '📦',
    tagline: 'Package lost or arrived damaged? Recover your money.',
    description: 'If a shipping carrier, retailer, or delivery service lost your package, delivered it damaged, or stole it, you can sue in small claims court for the full value of the contents plus any consequential damages.',
    commonScenarios: [
      'Package marked as delivered but never received',
      'Package arrived damaged',
      'Seller shipped wrong item and won\'t refund',
      'FedEx, UPS, or USPS lost your shipment',
      'Porch piracy — package stolen after delivery',
      'Perishable items arrived spoiled',
    ],
    whatYouNeed: [
      'Proof of purchase and item value',
      'Tracking information and delivery confirmation',
      'Photos of damaged packaging and contents',
      'Written communications with seller and carrier',
      'Insurance claim documentation',
      'Replacement cost receipts',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years depending on carrier type',
    tips: [
      'File a claim with the carrier immediately — there are short deadlines',
      'Keep all original packaging material',
      'Take photos before unpacking a damaged package',
      'You can sue both the seller AND the carrier',
    ],
  },
  {
    slug: 'insurance',
    title: 'Insurance Disputes',
    icon: '🛡️',
    tagline: 'Insurance company denying your claim? Fight back.',
    description: 'If your insurance company wrongfully denied your claim, underpaid you, or acted in bad faith, small claims court may be an option for smaller disputes. You can also sue for breach of contract when an insurer fails to honor a valid policy.',
    commonScenarios: [
      'Auto insurance claim denied or underpaid',
      'Renter\'s insurance claim wrongfully denied',
      'Health insurance refusing to cover treatment',
      'Home insurance underpaying for repairs',
      'Life insurance company delaying payment',
      'Policy cancelled unfairly',
    ],
    whatYouNeed: [
      'Your insurance policy documents',
      'Claim submission records',
      'Denial letter from the insurer',
      'Independent repair estimates or medical bills',
      'Photographs of damage',
      'All correspondence with the insurer',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years depending on policy type',
    tips: [
      'File a complaint with your state\'s Department of Insurance first',
      'Document every phone call with the insurance company',
      'Get independent estimates to counter lowball offers',
      'Request all claim decisions in writing',
    ],
  },
  {
    slug: 'stolen-property',
    title: 'Stolen Property',
    icon: '🔒',
    tagline: 'Your property was stolen. Make them pay.',
    description: 'If someone stole your property, you can sue them in small claims court for the fair market value of the stolen items, plus any related costs. This works alongside or instead of criminal proceedings.',
    commonScenarios: [
      'Former employee or tenant stole property',
      'Stolen property not returned after police recovery',
      'Theft by an acquaintance or business contact',
      'Stolen tools or equipment from a worksite',
      'Identity theft causing financial loss',
      'Conversion — someone taking your property without permission',
    ],
    whatYouNeed: [
      'Police report',
      'Proof of ownership',
      'Photos of the stolen items',
      'Receipts or appraisals showing value',
      'Evidence identifying the thief',
      'Records of any financial loss',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-3 years for conversion/theft civil claims',
    tips: [
      'File a police report immediately',
      'Keep records of serial numbers and purchase receipts for valuables',
      'Civil and criminal cases can run simultaneously',
      'You can sue for replacement value, not just original cost',
    ],
  },
  {
    slug: 'independent-contractor',
    title: 'Unpaid Independent Contractors',
    icon: '💼',
    tagline: 'You did the work. Now collect your money.',
    description: 'As a freelancer or independent contractor, you have the right to be paid for your work. If a client refuses to pay invoices, disputes your work without justification, or withholds payment, small claims court is fast and effective.',
    commonScenarios: [
      'Client refused to pay final invoice',
      'Client disputes scope of work after completion',
      'Partial payment received, rest withheld',
      'Client went out of business still owing money',
      'Work was completed but contract was cancelled without payment',
      'Late payment causing business losses',
    ],
    whatYouNeed: [
      'Signed contract or statement of work',
      'Invoices and payment records',
      'Proof of work completed',
      'Written communications with the client',
      'Time tracking records',
      'Any partial payments received',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-6 years depending on written vs oral agreement',
    tips: [
      'Always use written contracts, even simple ones',
      'Never deliver final work before receiving substantial payment',
      'Send invoices via email so you have proof of delivery',
      'A well-documented invoice trail is very compelling to judges',
    ],
  },
  {
    slug: 'airbnb',
    title: 'Airbnb Disputes',
    icon: '🏡',
    tagline: 'Bad Airbnb experience? You can sue the host — or Airbnb.',
    description: 'Airbnb disputes — whether you\'re a guest dealing with a terrible property or a host dealing with a destructive guest — are common in small claims court. Airbnb\'s internal resolution process is often unsatisfactory, but courts can compel actual payment.',
    commonScenarios: [
      'Property was nothing like the listing photos',
      'Host cancelled last minute leaving you stranded',
      'Property had safety hazards or health issues',
      'Security deposit wrongfully withheld by host',
      'Guest caused damage beyond normal wear',
      'Airbnb refused to honor their Host Guarantee',
    ],
    whatYouNeed: [
      'Listing screenshots and booking confirmation',
      'Photos or videos of the property condition',
      'Communications with the host through Airbnb',
      'Airbnb\'s resolution center correspondence',
      'Receipts for alternative accommodation',
      'Medical records if health/safety issue',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years',
    tips: [
      'Screenshot the listing before checking in',
      'Report issues to Airbnb within 24 hours of check-in',
      'Take photos the moment you arrive',
      'Airbnb can be named as a defendant alongside the host',
    ],
  },
  {
    slug: 'airlines',
    title: 'Airline Claims',
    icon: '✈️',
    tagline: 'Lost baggage, cancelled flight, denied boarding? Sue the airline.',
    description: 'Airlines are frequently sued in small claims court for lost baggage, flight cancellations, denied boarding, and failure to provide promised compensation. You don\'t need a lawyer, and airlines often settle rather than send lawyers to small claims court.',
    commonScenarios: [
      'Lost or damaged luggage',
      'Flight cancelled without adequate compensation',
      'Denied boarding on overbooked flight',
      'Significant delay causing additional expenses',
      'Failure to honor vouchers or flight credits',
      'Wheelchair or accessibility accommodation failures',
    ],
    whatYouNeed: [
      'Booking confirmation and boarding passes',
      'Baggage claim receipts',
      'Photos of damaged luggage or contents',
      'All correspondence with the airline',
      'Receipts for expenses caused by the disruption',
      'DOT complaint number if filed',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2 years for most airline claims',
    tips: [
      'File a DOT complaint before going to court',
      'Airlines often settle to avoid court appearances',
      'Under Montreal Convention, airlines owe up to ~$1,800 for lost baggage on international flights',
      'Keep all receipts for expenses caused by the disruption',
    ],
  },
  {
    slug: 'amazon',
    title: 'Amazon Disputes',
    icon: '📦',
    tagline: 'Amazon or its seller owes you. Small claims is your best bet.',
    description: 'You can sue Amazon in small claims court for defective products, unauthorized charges, account bans, and more. Small claims is often the only way around Amazon\'s arbitration clause, and Amazon frequently settles rather than sending lawyers.',
    commonScenarios: [
      'Defective product caused injury or damage',
      'Counterfeit product sold as genuine',
      'Unauthorized charges or subscription renewals',
      'Account wrongfully suspended as a seller',
      'Refund promised but never issued',
      'Prime membership fees after cancellation',
    ],
    whatYouNeed: [
      'Order confirmation and receipts',
      'Photos of defective or wrong item',
      'All communications with Amazon and sellers',
      'Medical records if injury occurred',
      'Bank statements showing charges',
      'Screenshots of account communications',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years',
    tips: [
      'Small claims courts have ruled Amazon cannot enforce arbitration clauses in these cases',
      'Amazon often settles before the court date',
      'File against both Amazon and the third-party seller if applicable',
      'A formal demand letter often gets results before you even file',
    ],
  },
  {
    slug: 'hotels',
    title: 'Hotel Disputes',
    icon: '🏨',
    tagline: 'Bad hotel experience? You may be owed a refund.',
    description: 'Hotels have a duty to provide safe, clean accommodations matching their descriptions. If a hotel failed to deliver what was promised, had safety issues, or wrongfully charged you, small claims court can help you recover.',
    commonScenarios: [
      'Room was nothing like advertised',
      'Hotel charged no-show fee for your stay',
      'Bed bugs or pest infestation',
      'Theft from room or safe',
      'Personal injury due to unsafe conditions',
      'Reservation cancelled without proper notice',
    ],
    whatYouNeed: [
      'Reservation confirmation',
      'Photos of room conditions',
      'Medical records for pest bite or injury',
      'Written complaints made during stay',
      'Credit card statements showing charges',
      'Screenshots of booking website listings',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years',
    tips: [
      'Report issues to the front desk immediately and in writing',
      'Take photos before unpacking',
      'Request a different room or full refund on the spot',
      'Contact Booking.com or Expedia if booked through a platform',
    ],
  },
  {
    slug: 'construction-defect',
    title: 'Construction Defects',
    icon: '🏗️',
    tagline: 'Contractor did shoddy work? Make them fix it — or pay.',
    description: 'Construction defects can range from cosmetic issues to serious structural problems. If a contractor did poor quality work, used inferior materials, violated building codes, or caused damage to your property, small claims court can help you recover.',
    commonScenarios: [
      'Roofing work that still leaks',
      'Flooring installation done incorrectly',
      'Contractor abandoned project after deposit',
      'Work failed inspection due to code violations',
      'Plumbing or electrical work causing damage',
      'Landscaping that caused drainage problems',
    ],
    whatYouNeed: [
      'Signed contract and scope of work',
      'Photos of defective work',
      'Building permits and inspection records',
      'Second contractor\'s written assessment',
      'Repair estimates to fix the defects',
      'All payments made to the contractor',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '3-10 years depending on defect type',
    tips: [
      'Always verify contractor license with the state licensing board',
      'Get lien waivers when making final payment',
      'In California, file a complaint with CSLB before court',
      'Document all construction phases with photos',
    ],
  },
  {
    slug: 'dental',
    title: 'Dental Malpractice',
    icon: '🦷',
    tagline: 'Bad dental work caused you harm? You have options.',
    description: 'Dental malpractice claims in small claims court typically cover situations where a dentist caused pain, injury, or additional costs through negligent treatment, unnecessary procedures, or failure to diagnose.',
    commonScenarios: [
      'Incorrect procedure performed',
      'Unnecessary dental work billed',
      'Post-procedure complications from negligence',
      'Billing fraud or overcharging',
      'Failure to diagnose treatable condition',
      'Damage to adjacent teeth during procedure',
    ],
    whatYouNeed: [
      'Your dental records',
      'X-rays before and after',
      'Second opinion from another dentist',
      'All bills and payment records',
      'Written complaints to the dental office',
      'Medical records for any related treatment',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-3 years for malpractice claims',
    tips: [
      'Get a written second opinion from another dentist',
      'Request your full dental records immediately',
      'File a complaint with the state dental board',
      'Expert testimony may be needed for complex cases',
    ],
  },
  {
    slug: 'travel-website',
    title: 'Travel Website Disputes',
    icon: '🌐',
    tagline: 'Expedia, Booking.com, or VRBO owe you a refund? Sue them.',
    description: 'Online travel platforms like Expedia, Booking.com, Hotels.com, and VRBO are frequently sued in small claims court for denied refunds, misrepresented listings, booking errors, and failure to deliver promised services.',
    commonScenarios: [
      'Refund denied for cancelled booking',
      'Property wasn\'t what was described',
      'Platform charged for reservation that wasn\'t honored',
      'Vouchers or credits not honored',
      'Double charge for same booking',
      'Customer service refusing to resolve legitimate complaint',
    ],
    whatYouNeed: [
      'Booking confirmation and receipts',
      'Screenshots of the original listing',
      'All communications with the platform',
      'Photos of the property or service received',
      'Credit card statements showing charges',
      'Cancellation policy documentation',
    ],
    maxAmount: { CA: '$12,500', TX: '$20,000', FL: '$8,000' },
    timeLimit: '2-4 years',
    tips: [
      'Screenshot everything at time of booking',
      'These companies often have arbitration clauses but small claims is generally exempt',
      'File complaints with the FTC and BBB alongside your court filing',
      'Travel platforms often settle quickly to avoid court',
    ],
  },
]

export function getClaimBySlug(slug: string): ClaimType | undefined {
  return CLAIMS.find(c => c.slug === slug)
}
